In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [18]:
df=pd.read_csv('IceCreamData.csv')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  500 non-null    float64
 1   Revenue      500 non-null    float64
dtypes: float64(2)
memory usage: 7.9 KB


In [20]:
df.isnull().sum()

Temperature    0
Revenue        0
dtype: int64

In [24]:
df.duplicated().sum()

0

In [22]:
X=df['Temperature']
Y=df['Revenue']
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [23]:
print(len(X_train))
print(len(X_test))
print(len(Y_train)) 
print(len(Y_test))

400
100
400
100


In [26]:
model=LinearRegression()
# linear regression requires target values in 1 dimension whereas the features to be in 2 dimensions.
# here ytrain is in 1 dimension and xtrain is also in 1 dimension
np.array([X_train]).ndim

2

In [27]:
model.fit(np.array([X_train]).reshape(-1,1),Y_train)

LinearRegression()

In [29]:
y_pred=model.predict(np.array([X_test]).reshape(-1,1))

In [30]:
y_pred

array([681.93870622, 632.14474995, 559.64360486, 498.90609993,
       615.45939165, 304.72417213, 285.79420948, 315.60842003,
       506.26427154, 685.69744019, 723.96030494, 400.84625166,
       431.61634142, 671.36600031,  52.51422053, 198.77682819,
       523.08595488, 563.90495549, 583.83579144, 682.24517768,
       556.2285085 , 783.88766163, 655.44109362, 570.0735459 ,
       912.21841974, 664.74778505, 315.96428407, 631.00983241,
       731.1169322 , 698.02984963, 435.08453949, 471.22058847,
       710.29440571, 799.81874771, 641.02153776, 493.66044553,
       744.9247237 , 318.10831232, 262.69083171, 132.04437543,
       582.55738268, 230.41054193, 547.29799783, 393.00654153,
       436.66704225, 593.02780835, 572.09312165, 125.16251036,
       474.79444877, 530.45025905, 623.19251713, 503.4813544 ,
       484.60103791, 498.58705266, 551.22738648, 630.80646076,
       573.12703075, 679.486141  , 171.29759926, 660.49458416,
       583.75017395, 704.57274239, 535.82240023, 630.12

In [31]:
Y_test

361    659.873287
73     623.248701
374    559.135869
155    497.752318
104    627.901841
          ...    
347    564.310532
86     643.944327
75     653.986736
438    412.082357
15     469.909033
Name: Revenue, Length: 100, dtype: float64

In [32]:
r2_score(Y_test,y_pred)

0.9771532792713993

In [34]:
model.predict([[34]])

array([773.79175236])

In [35]:
model.predict([[1]])

array([68.18661513])

In [36]:
with open('model.pkl','wb') as files:
    pickle.dump(model,files)
